name: Desktop Pull Request Check
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'FloconDesktop/**'
      - '.github/workflows/desktop_pr_check.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build FloconDesktop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: NucleusFramework/Nucleus/.github/actions/setup-nucleus@v2.3.0
      - name: Build with Gradle
        working-directory: FloconDesktop
        run: ./gradlew :composeApp:assemble
